# Generated by Django 5.0.7 on 2024-08-01 12:53

from django.db import migrations, models

import django_extensions.db.fields
import imagekit.models.fields

import config.settings.common.paths


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True,
                        verbose_name="modified",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=55,
                        unique=True,
                        verbose_name="Achievement",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to=config.settings.common.paths._default_media_path,
                        verbose_name="Achievement image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                verbose_name="Username",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="achievements",
            field=models.ManyToManyField(
                blank=True,
                help_text="Achievements that have this user",
                related_name="users",
                to="users.achievement",
                verbose_name="Achievements",
            ),
        ),
    ]
