# Generated by Django 5.0.7 on 2024-08-23 07:46

from django.db import migrations

import apps.users.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_achievement_user_created_at_user_username_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.user.UserManager()),
            ],
        ),
    ]
