# Generated by Django 5.0.7 on 2025-01-24 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("issues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                help_text="User's likes to comment",
                related_name="comments_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Comment likes",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User id",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                help_text="User's likes to issue",
                related_name="issues",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Issue likes",
            ),
        ),
        migrations.AddField(
            model_name="example",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examples",
                to="issues.issue",
                verbose_name="Issue",
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solutions",
                to="issues.issue",
                verbose_name="Issue",
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solutions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="solvedissue",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solved_issues",
                to="issues.issue",
                verbose_name="Issue",
            ),
        ),
        migrations.AddField(
            model_name="solvedissue",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solved_issues",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="tags",
            field=models.ManyToManyField(
                help_text="Tags that attached with issue",
                related_name="issues",
                to="issues.tag",
                verbose_name="Issue tags",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="issues.issue",
                verbose_name="Issue id",
            ),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="solution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases_results",
                to="issues.solution",
                verbose_name="Solution",
            ),
        ),
        migrations.AddField(
            model_name="testcaseresult",
            name="test_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases_results",
                to="issues.testcase",
                verbose_name="Test case",
            ),
        ),
        migrations.AddConstraint(
            model_name="example",
            constraint=models.UniqueConstraint(
                fields=("issue", "order"),
                name="unique_example_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="testcase",
            constraint=models.UniqueConstraint(
                fields=("issue", "order"),
                name="unique_task_order",
            ),
        ),
    ]
