# Generated by Django 5.0.7 on 2024-08-14 07:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0003_remove_tag_name_issue_complexity_tag_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True,
                        verbose_name="modified",
                    ),
                ),
                ("input", models.TextField(verbose_name="Input")),
                ("output", models.TextField(verbose_name="Output")),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="Explanation"),
                ),
                (
                    "order",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="issues.issue",
                        verbose_name="Issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Example",
                "verbose_name_plural": "Examples",
            },
        ),
        migrations.AddConstraint(
            model_name="example",
            constraint=models.UniqueConstraint(
                fields=("issue", "order"),
                name="unique_example_order",
            ),
        ),
    ]
