# Generated by Django 5.0.7 on 2024-08-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0004_example_example_unique_example_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="testing_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=15,
                verbose_name="Solution status",
            ),
        ),
    ]
